Core 195 - Disponibilizar SentOffers
vtex/mkp-app-template pull request #18
Opened 2021-08-27 12:44 UTC by jmscunha

- Deve oferecer Mecanismo deve ser disparado após clicar no botão salvar do formulário de configuração do APP
- Deve criar o feed caso este não exista e persisti-lo para o conector poder consumir na integração de catalogo

2021-08-30 14:59 UTC, luizaes commented on messages/context.json
> +  "admin/mkp-app-template.title": "Mkp App Template",
Aqui deveria continuar o placeholder né?
Acho que tu puxou essa branch da master que o @Kanchii atualizou depois, então vale fazer um merge/rebase aqui

2021-08-30 17:49 UTC, jmscunha commented on messages/context.json
> +  "admin/mkp-app-template.title": "Mkp App Template",
Perfeito Luiza! Já subi os ajustes, quando puder por favor, poderia dar uma olhada?

2021-08-30 19:09 UTC, luizaes commented on node/clients/sentOffers.ts
> +				throw new UserInputError('error.vtex.sentOffers')
```suggestion
				throw new UserInputError('admin/vtex.sentOffers')
```

2021-08-30 19:09 UTC, luizaes commented on node/resolvers/saveConfig.ts
> +  .catch( (_) => { throw new UserInputError("error.vtex.sentOffers") })
```suggestion
  .catch( (_) => { throw new UserInputError("admin/vtex.sentOffers") })                     
```

2021-08-30 19:59 UTC, Kanchii requested changes

2021-08-30 19:59 UTC, Kanchii commented on messages/context.json
> -  "admin/app.save": "Save",
Faltou só esse carinha aqui João, se puder adicionar ai

2021-08-30 19:59 UTC, Kanchii commented on messages/en.json
> -  "admin/app.save": "Save",
Faltou só esse carinha aqui João, se puder adicionar ai

2021-08-30 19:59 UTC, Kanchii commented on messages/es.json
> -  "admin/app.save": "Salvar",
Faltou só esse carinha aqui João, se puder adicionar ai

2021-08-30 19:59 UTC, Kanchii commented on messages/pt.json
> -  "admin/app.save": "Salvar",
Faltou só esse carinha aqui João, se puder adicionar ai

2021-08-30 19:59 UTC, Kanchii commented on messages/context.json
> +  "admin/app-template.cultureInfo.title": "Country",
aqui também daria pra trocar o "app-template" por "app", pra padronizar com oq estava antes tmb

2021-08-30 19:59 UTC, Kanchii commented on messages/en.json
> +  "admin/app-template.cultureInfo.title": "Country",
aqui também daria pra trocar o "app-template" por "app", pra padronizar com oq estava antes tmb

2021-08-30 19:59 UTC, Kanchii commented on messages/es.json
> +  "admin/app-template.cultureInfo.title": "País",
aqui também daria pra trocar o "app-template" por "app", pra padronizar com oq estava antes tmb

2021-08-30 19:59 UTC, Kanchii commented on messages/pt.json
> +  "admin/app-template.cultureInfo.title": "País",
aqui também daria pra trocar o "app-template" por "app", pra padronizar com oq estava antes tmb

2021-08-31 13:38 UTC, jmscunha commented on messages/context.json
> -  "admin/app.save": "Save",
Perfeito Weiss! subi as alterações

2021-08-31 22:09 UTC, Kanchii approved these changes
LGTM

2021-08-31 23:11 UTC, merged

2021-09-01 15:05 UTC, epklein reviewed
Feedback de alguns pontos que pude perceber no projeto.

2021-09-01 15:05 UTC, epklein commented on messages/es.json
> +  "admin/app.integrationStatus.tooltip": "Pausar o iniciar la integración con Amazon.",
Nome da integração específica

2021-09-01 15:05 UTC, epklein commented on messages/es.json
> +  "admin/vtex.sentOffers": "Se produjo un error al consumir la API de Sent Offers."
Nome do campo de erro

2021-09-01 15:05 UTC, epklein commented on messages/pt.json
> +  "admin/app.integrationStatus.tooltip": "Pausa ou inicia a integração com a Amazon.",
Nome específico